name: MessageMedia Messages SDK RubyGem

on:
  push:
    branches: [ "ruby_sdk_version3" ]
  pull_request:
    branches: [ "ruby_sdk_version3" ]

jobs:
  build:
    name: Install + Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.5','2.6','3.0','3.1']
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
      
    - name: Build gem
      run: gem build *.gemspec
      
    - uses: actions/upload-artifact@v3
      with:
       name: messages-ruby-sdk-artifact
       path: ./*.gem
