name: MessageMedia Messages SDK RubyGem

on:
  push:
    branches: [ "ruby_sdk_version3" ]
  pull_request:
    branches: [ "ruby_sdk_version3" ]

jobs:
  build:
    name: Install + Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0']
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
      
    - name: Build gem
      run: gem build *.gemspec
      
    - uses: actions/upload-artifact@v3
      with:
       name: messages-ruby-sdk-artifact
       path: ./*.gem
       
    - name: Publish to GPR
      run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
      env:
          GEM_HOST_API_KEY: "Bearer ${{secrets.GITHUB_TOKEN}}"
          OWNER: ${{ github.repository_owner }}   
